PORT=5000
// MONGO_URI=mongodb+srv:
//mathushanblazz:NEW_PASSWORD_HERE@cluster0.wl33uko.mongodb.net/?appName=Cluster0
JWT_SECRET=generate_a_new_strong_secret_here
OPENWEATHER_API_KEY=your_new_openweather_key
YOUTUBE_API_KEY=your_new_youtube_key
TWILIO_ACCOUNT_SID=your_new_twilio_sid
TWILIO_AUTH_TOKEN=your_new_twilio_token
// TWILIO_FROM_NUMBER=+13348101061  # This number might need to be re-provisioned
OTP_EXPIRY_MINUTES=5
// CLIENT_ORIGIN=http://localhost:5173